use_frameworks!

platform :ios, '9.0'

target 'YeasVideoImages_Example' do
  pod 'YeasVideoImages', :path => '../'

  target 'YeasVideoImages_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
